# Generated by Django 3.2.12 on 2024-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
        migrations.AddField(
            model_name='collector',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
